language: python
python:
    - 2.6
    - 2.7
before_install:
    - sudo apt-get update
    - sudo apt-get install libsqlite3-dev
    - sudo sh build/install_qt.sh
    - sh build/build_ui.sh
install: pip install -r requirements.txt --use-mirrors
script: sh build/tests.sh
branches:
    only:
        - master
        - develop
notifications:
    email:
        recipients:
            - russell.hay@gmail.com
        on_success: change
        on_failure: always
