language: python
python:
    - 2.6
    - 2.7
before_install:
    - sudo apt-get update
    - sudo apt-get install libsqlite3-dev
install: pip install -r requirements.txt --use-mirrors
script: cd pidatastore && python setup.py nosetests
branches:
    only:
        - master
        - develop
notifications:
    email:
        recipients:
            - russell.hay@gmail.com
        on_success: change
        on_failure: always
